#!bin/bash
# chmod command
echo "In Unix operating systems, the chmod command is used to change the access mode of a file. The name is an abbreviation of change mode. Which states that every file and directory has a set of permissions that control the permissions like who can read, write or execute the file. In this the permissions have three categories: read, write, and execute simultaneously represented by `r`, `w` and `x`. These letters combine together to form a specific permission for a group of users.

The `chmod` command is used to modify this permission so that it can grant or restrict access to directories and files. Let’s have a look at the syntax and options for the `chmod` command in Linux Operating System.

Syntax:

chmod [options] [mode] [File_name] "